services:
  - type: web
    name: dianshang
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PUBLIC_HOST
        valueFrom:
          type: env
          envKey: RENDER_EXTERNAL_HOSTNAME